#include "maptranslator.h"
#include <QHash>
#include <QStringList>
#include <QGuiApplication>
#include <QClipboard>

namespace {
static const struct { const char *name; const char *zh; const char *diff; } kTranslations[] = {
    {"ze__hell_p", u8"无尽的地狱", u8"普通"},
    {"ze_1_schizo", u8"思觉失调", u8"困难"},
    {"ze_1way_tunnel", u8"单向隧道", u8"困难"},
    {"ze_20_seconds_diamond_patch", u8"20秒防守战", u8"普通"},
    {"ze_2012_p", u8"2012世界末日", u8"简单"},
    {"ze_203_factory", u8"203化学工厂", u8"普通"},
    {"ze_2049", u8"2049", u8"梦魇"},
    {"ze_30_seconds_p", u8"生死30秒", u8"简单"},
    {"ze_8bit", u8"8bit世界", u8"极难"},
    {"ze_a_e_s_t_h_e_t_i_c_p", u8"舞台剧", u8"梦魇"},
    {"ze_abandoned_industry_p", u8"废弃工厂", u8"普通"},
    {"ze_act_character_relic", u8"序章：遗迹", u8"史诗"},
    {"ze_aepp_nano_grid2_p", u8"纳米世界", u8"普通"},
    {"ze_alien_mountain_escape_ffvii_v5", u8"阿里山逃亡(FF版)", u8"普通"},
    {"ze_alien_mountain_escape_p", u8"阿里山", u8"简单"},
    {"ze_alien_shooter", u8"孤胆枪手", u8"困难"},
    {"ze_amdaporkeep", u8"最终幻想14:无限城古堡", u8"史诗"},
    {"ze_ancient_wrath_p", u8"古代种金字塔", u8"梦魇"},
    {"ze_angelbeats_guild", u8"天使的心跳", u8"困难"},
    {"ze_angels_of_death", u8"杀戮天使", u8"史诗"},
    {"ze_antartika_p", u8"南极基地", u8"困难"},
    {"ze_anzalone_bridge_rewind", u8"安扎隆长桥倒影", u8"普通"},
    {"ze_anzalone_remake", u8"安扎隆断后长廊", u8"简单"},
    {"ze_aooka", u8"龙之殿", u8"梦魇"},
    {"ze_aoraitsu_reloaded", u8"流光幻境", u8"极难"},
    {"ze_aot_trost_v6r", u8"进击的巨人", u8"史诗"},
    {"ze_aperturescience_p", u8"光圈科技", u8"简单"},
    {"ze_apollo_p", u8"阿波罗登月计划", u8"简单"},
    {"ze_apprehended", u8"逃出拘留所", u8"困难"},
    {"ze_aragami_p", u8"荒神", u8"普通"},
    {"ze_arcana_heart", u8"阿卡纳之心", u8"史诗"},
    {"ze_arctic_escape_p", u8"北极逃亡", u8"简单"},
    {"ze_ardenweald", u8"魔兽世界：炽蓝仙野", u8"极难"},
    {"ze_arknights_caerula_arbor", u8"明日方舟：水月与深蓝之树", u8"极难"},
    {"ze_arknights_initium", u8"明日方舟：序章", u8"困难"},
    {"ze_arknights_sows", u8"明日方舟：大荒城", u8"普通"},
    {"ze_artika_base_p", u8"阿提卡基地", u8"困难"},
    {"ze_ashen_keep_p", u8"黑暗之魂：亚诺尔隆德", u8"极难"},
    {"ze_atix_apocalypse_p", u8"黑鹰坠落:归来", u8"普通"},
    {"ze_atix_panic_2017_p", u8"牢大逃亡2017", u8"简单"},
    {"ze_atix_panic_2077", u8"牢大逃亡2077", u8"困难"},
    {"ze_atix_panic_p", u8"牢大逃亡", u8"普通"},
    {"ze_atl_lgnition_a1", u8"湮灭影像：起源", u8"困难"},
    {"ze_atos", u8"阿托斯", u8"史诗"},
    {"ze_avalanche_reboot", u8"雪崩再临:暗区突围", u8"史诗"},
    {"ze_awaker", u8"觉醒者", u8"极难"},
    {"ze_aware", u8"无限回廊先知圣地", u8"极难"},
    {"ze_azathoth_p", u8"阿撒托斯", u8"普通"},
    {"ze_aztecnoob_p", u8"阿兹特克遗迹", u8"简单"},
    {"ze_baboon_escape_cs2", u8"狒狒神庙", u8"困难"},
    {"ze_backroom_level4_v1", u8"后室：第四层级", u8"普通"},
    {"ze_backrooms", u8"后室：轮回之地", u8"史诗"},
    {"ze_backrooms_deathbed_v1", u8"后室：死眠", u8"极难"},
    {"ze_backrooms_insomnia", u8"后室：失眠症", u8"梦魇"},
    {"ze_backrooms_run", u8"后室level!", u8"困难"},
    {"ze_baldi", u8"巴迪", u8"普通"},
    {"ze_bang_dream_mygo", u8"爱音の梦", u8"困难"},
    {"ze_barrage_p", u8"求生之路-大坝", u8"普通"},
    {"ze_basic_geometric", u8"基本几何", u8"梦魇"},
    {"ze_bathroom", u8"浴室逃亡", u8"普通"},
    {"ze_beyond_horizon", u8"海洋彼岸", u8"极难"},
    {"ze_beyond_the_boundary", u8"境界彼方", u8"困难"},
    {"ze_bh3rd_babel_z", u8"崩坏3:巴比伦塔", u8"困难"},
    {"ze_bh3rd_cyberpunk_z", u8"崩坏3:天穹市", u8"困难"},
    {"ze_bh3rd_nagazoracity_z", u8"崩坏3:长空市", u8"普通"},
    {"ze_bible_adventure_ot_p", u8"圣经大冒险", u8"普通"},
    {"ze_bigboo_n64", u8"超级马里奥之闹鬼小屋", u8"普通"},
    {"ze_biohazard_manor_004_p", u8"生化危机：洋馆", u8"普通"},
    {"ze_biohazard2_rpd_004_p", u8"生化危机：警察局", u8"普通"},
    {"ze_biohazard2_sewer_004", u8"生化危机2：下水道", u8"普通"},
    {"ze_bioluminescent", u8"荧光生物", u8"史诗"},
    {"ze_bioshock_v6_cs2", u8"生化奇兵v6", u8"史诗"},
    {"ze_bisounours_party", u8"彩虹岛", u8"普通"},
    {"ze_black_lion_p", u8"黑狮", u8"普通"},
    {"ze_blackmesa_escape_p", u8"黑山基地：重装上阵", u8"简单"},
    {"ze_blackmesa_remix_cs2", u8"黑山基地remix：重装上阵", u8"普通"},
    {"ze_blood_castle", u8"血色城堡", u8"简单"},
    {"ze_blue_magic_castle", u8"蓝色魔法城堡", u8"极难"},
    {"ze_bluearchive_abydos_b1", u8"碧蓝档案：总力战(旧版)", u8"困难"},
    {"ze_boacceho_p", u8"boacceho逃亡", u8"简单"},
    {"ze_boatescape_ultimate", u8"终极坐船跑：明星大乱斗", u8"困难"},
    {"ze_boatescape777", u8"开心快乐坐船跑777", u8"普通"},
    {"ze_boatescape888", u8"开心快乐坐船跑888", u8"简单"},
    {"ze_boatescape999", u8"开心快乐坐船跑999", u8"简单"},
    {"ze_boralus", u8"魔兽世界：伯拉勒斯", u8"史诗"},
    {"ze_box_cloaca_b1", u8"盒子：地下室", u8"普通"},
    {"ze_box_defend_v1_4", u8"代号：盒子防守v1.4", u8"简单"},
    {"ze_bp-infested-prison_p", u8"监狱逃亡", u8"简单"},
    {"ze_breakable_p", u8"随处可破坏的箱子", u8"普通"},
    {"ze_breakdream", u8"破碎之梦", u8"极难"},
    {"ze_candyfactory", u8"糖果工厂", u8"史诗"},
    {"ze_castle_bridge_p", u8"古堡大桥", u8"史诗"},
    {"ze_castlevania", u8"恶魔城传说", u8"史诗"},
    {"ze_castlevania_nes", u8"恶魔城NES版", u8"梦魇"},
    {"ze_celestial_ops", u8"天堂", u8"困难"},
    {"ze_cfguilai_v1_0", u8"CF王者归来", u8"普通"},
    {"ze_challenge_run", u8"随机挑战逃亡", u8"普通"},
    {"ze_changed", u8"兽化实验室", u8"极难"},
    {"ze_chicken_lords_tower_p", u8"大只因城堡", u8"普通"},
    {"ze_chicken_nugget", u8"豪大的只因块", u8"简单"},
    {"ze_chip_n_dale", u8"FC松鼠大作战", u8"普通"},
    {"ze_christmas_escape", u8"圣诞小逃亡", u8"普通"},
    {"ze_christmas_infection_p", u8"圣诞惊魂夜", u8"困难"},
    {"ze_christmas_p", u8"圣诞小镇", u8"困难"},
    {"ze_chronicle_a", u8"四叶草遗址", u8"极难"},
    {"ze_chrono_trigger", u8"时空之轮", u8"困难"},
    {"ze_chronoplague_v12", u8"时空瘟疫", u8"困难"},
    {"ze_chronus_p", u8"克罗诺斯山谷", u8"普通"},
    {"ze_circle", u8"萌新爱转圈", u8"普通"},
    {"ze_clawfactory", u8"蟹老板工厂", u8"普通"},
    {"ze_clockwork", u8"时钟工坊", u8"极难"},
    {"ze_color_levels", u8"颜色关卡保卫战", u8"困难"},
    {"ze_colorful", u8"黑白的绚烂", u8"史诗"},
    {"ze_colorlicouspilar_p", u8"彩虹塔", u8"普通"},
    {"ze_colors_p", u8"搞颜色", u8"普通"},
    {"ze_compound_escape", u8"逃离化学工厂", u8"普通"},
    {"ze_conflict", u8"公交车", u8"极难"},
    {"ze_contradiction_spiral", u8"矛盾螺旋", u8"极难"},
    {"ze_coolcoolsnowman_n64", u8"超级马里奥之酷冰冰雪山之旅", u8"普通"},
    {"ze_crashbandicoot_p", u8"古惑狼", u8"普通"},
    {"ze_crazy_christmas_p", u8"疯狂圣诞节", u8"困难"},
    {"ze_croc2_sailor_village", u8"超级克拉鳄2：水手村", u8"困难"},
    {"ze_cry_thunder", u8"安扎隆长桥倒影", u8"普通"},
    {"ze_cube_defense", u8"方块防守战", u8"普通"},
    {"ze_cursed_bear_tales", u8"诅咒熊传说", u8"史诗"},
    {"ze_cyberspace_v2", u8"赛博空间", u8"史诗"},
    {"ze_dabadeedabadie", u8"忧郁的蓝：大坝的打坝爹", u8"困难"},
    {"ze_dangerous_waters_p", u8"危险水域", u8"普通"},
    {"ze_dark_souls", u8"黑暗之魂1", u8"绝境"},
    {"ze_darkest_hour", u8"至暗时刻", u8"极难"},
    {"ze_date_a_live", u8"约会大作战", u8"史诗"},
    {"ze_deadcore", u8"死亡核心", u8"梦魇"},
    {"ze_deadcore_r", u8"死亡核心[R]", u8"绝境"},
    {"ze_dear", u8"月神殿", u8"普通"},
    {"ze_death_forest", u8"恐怖之森", u8"普通"},
    {"ze_death_star_escape_p", u8"死星逃亡", u8"简单"},
    {"ze_deathinvain_palace", u8"死者宫殿", u8"史诗"},
    {"ze_decayed_dreams", u8"腐朽的梦", u8"普通"},
    {"ze_decayed_dreams2", u8"腐朽之梦·续章", u8"困难"},
    {"ze_deepice_p", u8"深井冰", u8"普通"},
    {"ze_defend_truck_v1", u8"卡车防守", u8"简单"},
    {"ze_defense3002_p", u8"代号：防守 V300_2", u8"简单"},
    {"ze_depths", u8"冥城：深入地下城", u8"梦魇"},
    {"ze_descent_into_cerberon_p", u8"破碎行动", u8"困难"},
    {"ze_desert_tour_cs2", u8"游历沙漠之旅", u8"困难"},
    {"ze_desperate_soul", u8"异闻录：母神悲歌", u8"困难"},
    {"ze_destruction_of_exorath", u8"死亡空间", u8"困难"},
    {"ze_devil_may_cry", u8"鬼泣五", u8"史诗"},
    {"ze_diablo", u8"暗黑破坏神", u8"梦魇"},
    {"ze_diamond_cube_v1_cs2", u8"钻石立方体", u8"极难"},
    {"ze_diddle", u8"欺骗", u8"梦魇"},
    {"ze_diverted_destiny", u8"反抗命运的序曲", u8"梦魇"},
    {"ze_djinn", u8"法老陵墓", u8"极难"},
    {"ze_dnb_realms_a1", u8"鼓与贝斯的领域之境", u8"史诗"},
    {"ze_dnd_hydra_z", u8"龙与地下城：海德拉", u8"困难"},
    {"ze_doom", u8"毁灭战士", u8"普通"},
    {"ze_doomglaven", u8"战锤：末世鼠疫", u8"困难"},
    {"ze_dorororo", u8"和doro一起夺回orange", u8"困难"},
    {"ze_downstairs", u8"萌新爱下楼", u8"极难"},
    {"ze_dragonball_snakeway_p", u8"龙珠：蛇道", u8"普通"},
    {"ze_drakelord_castle_b3", u8"地龙城堡", u8"梦魇"},
    {"ze_dreamin", u8"梦想", u8"史诗"},
    {"ze_dystopia_p", u8"敌托邦", u8"困难"},
    {"ze_easy_escape_v4", u8"简单逃亡", u8"困难"},
    {"ze_einstein", u8"爱因斯坦", u8"困难"},
    {"ze_eizures_b1_1", u8"核子危机", u8"极难"},
    {"ze_eizures_b2", u8"核子危机：新征程", u8"史诗"},
    {"ze_elevator_escape_p", u8"电梯逃亡", u8"简单"},
    {"ze_elmas", u8"钻石", u8"史诗"},
    {"ze_embertwin_v1", u8"余烬双星：眼之回响之放生四眼鱼会让挪麦人梦到电子鹿吗", u8"绝境"},
    {"ze_emerald", u8"绿宝石宫殿", u8"困难"},
    {"ze_emiya_re", u8"雪下的誓言", u8"史诗"},
    {"ze_empirecity_p", u8"帝国都市", u8"普通"},
    {"ze_best_korea_p", u8"最美曹县", u8""},
    {"ze_endless_dream", u8"无尽之梦", u8"史诗"},
    {"ze_endor", u8"恩多", u8"史诗"},
    {"ze_error", u8"错误大逃亡", u8"普通"},
    {"ze_escape_the_eye_p", u8"逃离天眼", u8"普通"},
    {"ze_escape2024", u8"智勇大冲关2024", u8"困难"},
    {"ze_escapetheworld", u8"逃离异世界", u8"极难"},
    {"ze_eternal_grove", u8"永恒之森", u8"梦魇"},
    {"ze_eternal_journey", u8"飞升者：永恒旅途", u8"史诗"},
    {"ze_evernight", u8"永夜", u8"史诗"},
    {"ze_evil_mansion_p", u8"邪恶公馆", u8"简单"},
    {"ze_exchange_innovation_p", u8"逃离生化大楼", u8"普通"},
    {"ze_exit_this_earths_atomosphere_p", u8"逃出大气层", u8"史诗"},
    {"ze_rt4_hessel_valley", u8"时雨4：希赛尔山谷", u8"史诗"},
    {"ze_exit8", u8"逃离8号出口", u8"简单"},
    {"ze_eye_factory_escape", u8"独眼工厂逃亡", u8"困难"},
    {"ze_eye_for_an_eye_v22", u8"以眼还眼", u8"极难"},
    {"ze_ez_run", u8"娱乐主义时代", u8"困难"},
    {"ze_fall_guys", u8"[娱乐]糖豆人", u8"极难"},
    {"ze_fantasy_escape", u8"幻想娱乐大逃亡", u8"普通"},
    {"ze_fapescape_katrina", u8"乐高逃亡:katrina", u8"史诗"},
    {"ze_fapescape_p", u8"旧乐高大逃亡", u8"极难"},
    {"ze_fapescape_rote_p", u8"新乐高逃亡：噩梦陷阱", u8"梦魇"},
    {"ze_farmhouse_p", u8"坦克农场", u8"困难"},
    {"ze_fast_escape_p", u8"fast逃亡", u8"简单"},
    {"ze_fe8_sacred_stones", u8"火焰之纹章:圣魔之光石", u8"极难"},
    {"ze_ff_legend_trial", u8"最终幻想大杂烩", u8"绝境"},
    {"ze_ffvii_cosmo_canyon_t", u8"最终幻想7：宇宙峡谷", u8"极难"},
    {"ze_ffvii_cosmo_canyon_v5_p", u8"最终幻想7：宇宙峡谷v5", u8"史诗"},
    {"ze_ffvii_mako_reactor_v5_3", u8"最终幻想7：魔光炉V53", u8"极难"},
    {"ze_ffvii_mako_reactor_v6_p", u8"最终幻想7：魔光炉V6", u8"史诗"},
    {"ze_ffvii_malgo_reactor", u8"最终幻想7：Malgo魔光炉", u8"史诗"},
    {"ze_ffvii_snow_cosmo", u8"最终幻想7：雪地峡谷", u8"极难"},
    {"ze_ffvii_temple_ancient", u8"最终幻想7：古代种神殿v5", u8"极难"},
    {"ze_ffxii_feywood_t", u8"最终幻想12：幻妖之森", u8"极难"},
    {"ze_ffxii_mt_bur_omisace_v6", u8"最终幻想12：神都布尔奥米赛斯V6", u8"史诗"},
    {"ze_ffxii_paramina_rift", u8"最终幻想12：帕拉米纳大峡谷", u8"极难"},
    {"ze_ffxii_westersand_v7_t", u8"最终幻想12：西沙v7", u8"史诗"},
    {"ze_ffxii_westersand_v8", u8"最终幻想12：西沙v8", u8"史诗"},
    {"ze_ffxiv_coil_of_bahamut", u8"最终幻想14:巴哈姆特大迷宫", u8"史诗"},
    {"ze_ffxiv_great_gubal_library", u8"最终幻想14:迦巴勒幻想图书馆", u8"史诗"},
    {"ze_ffxiv_pharos_sirius", u8"最终幻想14：领航明灯天狼星灯塔", u8"史诗"},
    {"ze_ffxiv_pharos_sirius_night", u8"最终幻想14:天狼星灯塔[CSGO版]", u8"史诗"},
    {"ze_ffxiv_reisen_temple", u8"最终幻想14：醴泉神社", u8"极难"},
    {"ze_ffxiv_the_orbonne_monastery", u8"最终幻想14：乐欲之所瓯博讷修道院", u8"史诗"},
    {"ze_ffxiv_wanderers_palace_v5_2", u8"最终幻想14：放浪古神殿v5", u8"史诗"},
    {"ze_ffxiv_wanderers_palace_v6_2", u8"最终幻想14：放浪古神殿v6", u8"史诗"},
    {"ze_fireboy_watergirl", u8"森林冰火人", u8"普通"},
    {"ze_firewall_laboratory_part1_p", u8"紧张刺激防火墙1", u8"简单"},
    {"ze_firewall_laboratory_part2_p", u8"防火墙2", u8"简单"},
    {"ze_flex_p", u8"随机防守", u8"普通"},
    {"ze_floating_rocks_survival", u8"浮空岛生存", u8"普通"},
    {"ze_flower", u8"FLOWER", u8"极难"},
    {"ze_flowering", u8"月神殿:前传", u8"普通"},
    {"ze_flying_world", u8"空岛世界", u8"普通"},
    {"ze_fond_dream", u8"南柯一梦", u8"极难"},
    {"ze_forestbunkers_p", u8"森林地堡", u8"普通"},
    {"ze_forhidden_slicoo_cs2", u8"禁地斯狄科", u8"梦魇"},
    {"ze_forhidden_void", u8"禁地：虚空遗迹", u8"史诗"},
    {"ze_forius_just_run_p", u8"不要害怕只管跑", u8"普通"},
    {"ze_forsaken_temple", u8"遗忘神殿", u8"极难"},
    {"ze_fragment_ops_rewind", u8"破碎数码", u8"史诗"},
    {"ze_frostdrake_tower_p", u8"寒霜高塔", u8"史诗"},
    {"ze_frozen_abyss", u8"冰封深渊", u8"梦魇"},
    {"ze_frozentemple_cs2", u8"冰封神庙", u8"困难"},
    {"ze_funny_runner", u8"娱乐赛跑", u8"普通"},
    {"ze_games_p", u8"小游戏合集", u8"简单"},
    {"ze_gameshow", u8"游戏真人秀", u8"普通"},
    {"ze_gear_palace", u8"齿轮宫殿", u8"困难"},
    {"ze_genso_of_last_v3", u8"遥远的幻想乡", u8"史诗"},
    {"ze_geometric", u8"几何奥秘", u8"极难"},
    {"ze_gettingoverit", u8"掘地求升", u8"困难"},
    {"ze_gods_wrath_p", u8"神怒", u8"简单"},
    {"ze_goldeneye_64", u8"零零柒:黄金眼", u8"困难"},
    {"ze_golubenkaya_meow", u8"戈卢本卡亚猫咪神殿", u8"极难"},
    {"ze_grace", u8"优雅", u8"极难"},
    {"ze_grau_p", u8"格劳", u8"极难"},
    {"ze_greece_escape_p", u8"希腊逃亡", u8"简单"},
    {"ze_greencity_p", u8"绿之城", u8"简单"},
    {"ze_gris_p", u8"格里斯", u8"史诗"},
    {"ze_gtasa_police_station_remix_m", u8"GTA警察局", u8"困难"},
    {"ze_gugugaga_escape", u8"重生之我在咕咕嘎嘎世界逃亡", u8"简单"},
    {"ze_halloween_house_p", u8"万圣屋", u8"极难"},
    {"ze_halo3_thestorm", u8"光环3:风暴来临", u8"困难"},
    {"ze_hammer_bunker_part1", u8"锤子地堡", u8"普通"},
    {"ze_happiness_factory", u8"幸福工厂：前传", u8"史诗"},
    {"ze_happiness_factory_v2", u8"幸福工厂：后传", u8"史诗"},
    {"ze_haunted_lab_escape_p", u8"闹鬼实验室", u8"普通"},
    {"ze_hazard_escape_p", u8"炸桥传奇2", u8"简单"},
    {"ze_hell_escape_p", u8"地狱逃亡", u8"普通"},
    {"ze_hidden_fortress_p", u8"隐秘要塞", u8"普通"},
    {"ze_highest_to_lowest", u8"猛虎下山", u8"简单"},
    {"ze_hlc_citadel_v1", u8"hlc城堡", u8"普通"},
    {"ze_hr_dead_center", u8"求生之路:死亡中心", u8"困难"},
    {"ze_hsc", u8"HSC方块世界", u8"史诗"},
    {"ze_hydroponic_garden", u8"水培花园", u8"史诗"},
    {"ze_hypernova_p", u8"超新星", u8"普通"},
    {"ze_iamlegend_p", u8"我是炸桥传奇", u8"普通"},
    {"ze_ice_cavern_z", u8"塞尔达：冰雪神殿", u8"史诗"},
    {"ze_ice_hold_p", u8"雪地防守", u8"普通"},
    {"ze_icebreaker", u8"鸡哥手撕战列舰", u8"普通"},
    {"ze_icecap_escape_ia_super", u8"[娱乐]西瓜橘子坐船跑(超级版)", u8"困难"},
    {"ze_icecap_escape_p", u8"西瓜橘子坐船跑", u8"简单"},
    {"ze_iceskate", u8"溜冰大乱斗", u8"普通"},
    {"ze_iceworld_athletic_cs2", u8"冰雪竞技场", u8"困难"},
    {"ze_illusory_world", u8"虚空幻界", u8"极难"},
    {"ze_immortal_flame", u8"永恒烈焰", u8"极难"},
    {"ze_imperial_sanctum", u8"皇城圣地", u8"极难"},
    {"ze_imperium", u8"战锤40k:帝国", u8"极难"},
    {"ze_inboxed_p", u8"inbox追击", u8"困难"},
    {"ze_incident_seasons", u8"四季异变章", u8"史诗"},
    {"ze_indiana_jones_004_p", u8"夺宝奇兵", u8"普通"},
    {"ze_industrial_dejavu", u8"工业循环", u8"普通"},
    {"ze_infected_sewers_v4", u8"合金弹头：下水道", u8"困难"},
    {"ze_infested-industry_p", u8"受感染的工厂", u8"普通"},
    {"ze_infiltration_final_p", u8"潜入行动", u8"困难"},
    {"ze_insanitycity_t", u8"疯狂之城", u8"普通"},
    {"ze_interception_p", u8"拦截行动", u8"困难"},
    {"ze_isla_nublar_p", u8"侏罗纪公园：努布拉岛", u8"困难"},
    {"ze_italy_town_z", u8"意大利小镇", u8"普通"},
    {"ze_jiangnan_town_v3_1", u8"江南水乡", u8"普通"},
    {"ze_journey_p", u8"黑暗之魂：旅途", u8"极难"},
    {"ze_jurassic_life", u8"侏罗纪生存记", u8"普通"},
    {"ze_jurassic_park_story_p", u8"侏罗纪公园：故事篇", u8"普通"},
    {"ze_jurassicpark_escape_p", u8"侏罗纪公园2", u8"普通"},
    {"ze_jurassicpark_p", u8"侏罗纪公园", u8"普通"},
    {"ze_k19_escape_p", u8"k19逃亡", u8"简单"},
    {"ze_kaffe_escape_p", u8"咖啡逃亡", u8"简单"},
    {"ze_kage_cs2", u8"赤影战士", u8"困难"},
    {"ze_kebab_immigrant", u8"争夺烤肉", u8"极难"},
    {"ze_kenshin_v1", u8"恸哭之星", u8"极难"},
    {"ze_knife_stray_p", u8"刀战竞技场", u8"普通"},
    {"ze_kitchen", u8"巨人厨房", u8"梦魇"},
    {"ze_kororinpa", u8"弹珠迷宫", u8"普通"},
    {"ze_l0v0l_p", u8"颜文字1 - l0v0l", u8"梦魇"},
    {"ze_lab_cs2_l", u8"实验室惊魂", u8"简单"},
    {"ze_laser_island_z", u8"跳刀岛", u8"困难"},
    {"ze_last_man_standing_p", u8"一人之巅", u8"梦魇"},
    {"ze_legend_of_astrum_z", u8"公主连结！：阿斯特朗传奇", u8"极难"},
    {"ze_legends_of_dawn", u8"黎明传说", u8"普通"},
    {"ze_lego", u8"马乐高之旅", u8"梦魇"},
    {"ze_legoland_crackheads", u8"乐高游乐场", u8"普通"},
    {"ze_lemonade", u8"冰鲜柠檬水", u8"困难"},
    {"ze_lemonysnickets_p", u8"雷蒙·斯尼奇历险", u8"普通"},
    {"ze_lethal_company", u8"致命公司", u8"普通"},
    {"ze_licciana_escape_p", u8"里西西亚", u8"普通"},
    {"ze_light_shadow_cs2", u8"光与影", u8"史诗"},
    {"ze_lightnight_v1", u8"光与暗", u8"极难"},
    {"ze_lila_panic_escape_p", u8"里拉逃亡", u8"史诗"},
    {"ze_little_trip", u8"小小旅途", u8"普通"},
    {"ze_loom", u8"恐惧隐现", u8"困难"},
    {"ze_lootus_v1_2", u8"水中城堡", u8"困难"},
    {"ze_lost_ruins", u8"失落遗迹", u8"普通"},
    {"ze_lostclue_cs2_l", u8"csol异乱之战", u8"普通"},
    {"ze_lotr_helms_deep_p", u8"魔戒：圣盔谷之战", u8"普通"},
    {"ze_lotr_isengard", u8"魔戒：艾辛格", u8"极难"},
    {"ze_lotr_minas_tiret_p", u8"魔戒：米纳斯议会", u8"普通"},
    {"ze_lotr_minas_tirith_cs2", u8"魔戒：米那斯提力斯(L版)", u8"梦魇"},
    {"ze_lotr_mines_of_moria_p", u8"魔戒：摩瑞亚矿坑", u8"普通"},
    {"ze_lotr_mirkwood_p", u8"魔戒：幽暗密林", u8"困难"},
    {"ze_lotr_mount_doom_p", u8"魔戒：末日火山", u8"困难"},
    {"ze_luciddreams_cs2", u8"清醒梦", u8"极难"},
    {"ze_luigismansion_p", u8"路易基鬼屋", u8"普通"},
    {"ze_luminous_escape", u8"霓虹逃生", u8"极难"},
    {"ze_mabinogi_f4_1_cs2", u8"洛奇", u8"普通"},
    {"ze_madara_temple", u8"宇智波·斑神殿", u8"史诗"},
    {"ze_madness", u8"暴力迪吧", u8"普通"},
    {"ze_magala_castle_p", u8"玛格拉城堡", u8"普通"},
    {"ze_magic_carpet_p", u8"魔毯世界", u8"困难"},
    {"ze_magmadrake_b4", u8"熔岩高塔", u8"梦魇"},
    {"ze_magus_v2_4", u8"魔法森林", u8"普通"},
    {"ze_maontain_escape", u8"哈基米曼波山", u8"困难"},
    {"ze_mario_tower_p", u8"马里奥之塔", u8"普通"},
    {"ze_mars_escape_p", u8"火星逃亡", u8"简单"},
    {"ze_mars_escape_xmas", u8"圣诞版火星逃亡(大杂烩)", u8"史诗"},
    {"ze_maze_runner", u8"移动迷宫", u8"普通"},
    {"ze_mc_museum", u8"我的世界：鼠鼠博物馆", u8"普通"},
    {"ze_melong_dow_learjet_p", u8"里尔喷气机惊险逃亡", u8"简单"},
    {"ze_mgden_z", u8"曼尼福德花园", u8"史诗"},
    {"ze_military_escape_p", u8"逃离军事工厂", u8"普通"},
    {"ze_mindtree", u8"智慧树", u8"极难"},
    {"ze_minecraft_adventure", u8"我的世界：大冒险", u8"普通"},
    {"ze_minecraft_dragon_castle", u8"我的世界：神龙城堡", u8"困难"},
    {"ze_minecraft_dreamland", u8"我的世界：梦境", u8"困难"},
    {"ze_minecraft_drifts", u8"我的世界：漂流", u8"普通"},
    {"ze_minecraft_escape", u8"我的世界：大逃杀", u8"简单"},
    {"ze_minecraft_flood_escape", u8"我的世界：洪水逃离", u8"史诗"},
    {"ze_minecraft_hortus_de_escapism", u8"我的世界：雾林镇的阴霾", u8"困难"},
    {"ze_minecraft_hortus_de_escapismo", u8"我的世界：雾林镇的阴霾", u8"困难"},
    {"ze_minecraft_lucky_blocks", u8"我的世界:幸运方块", u8"简单"},
    {"ze_minecraft_manor_panic", u8"我的世界：宅邸防守战", u8"简单"},
    {"ze_minecraft_p", u8"我的世界", u8"简单"},
    {"ze_minecraft_run", u8"我的世界：生死时速", u8"普通"},
    {"ze_minecraft_sakura", u8"我的世界：撒库拉岛", u8"普通"},
    {"ze_minecraft_superflat_v1", u8"我的世界：超平坦世界", u8"普通"},
    {"ze_minecraft_universe", u8"我的世界：宇宙前传", u8"普通"},
    {"ze_minecratix", u8"我的世界：高端防守战", u8"简单"},
    {"ze_minimal", u8"极病", u8"史诗"},
    {"ze_mirrors_edge_reborn_p", u8"镜之边缘：跑酷重生", u8"困难"},
    {"ze_misaka", u8"御坂大冒险1", u8"极难"},
    {"ze_misaka2_reborn", u8"御坂大冒险2（重生）", u8"史诗"},
    {"ze_miside", u8"米塔 Miside", u8"困难"},
    {"ze_mission_escape", u8"雪地逃亡", u8"普通"},
    {"ze_mist_p", u8"雾城龙影", u8"极难"},
    {"ze_misty_lake", u8"迷雾之湖", u8"极难"},
    {"ze_mix", u8"灾星纪元", u8"梦魇"},
    {"ze_mkzk_scarab_v4", u8"重生之我在ZE倒斗-究极无敌折磨之圣甲虫法老王金字塔V4", u8"绝境"},
    {"ze_mochi_island", u8"年糕岛", u8"困难"},
    {"ze_mojos_minigames_p", u8"魔力小游戏", u8"普通"},
    {"ze_moltentemple", u8"熔火神庙", u8"梦魇"},
    {"ze_moonshadow_ex", u8"月影传说EX", u8"史诗"},
    {"ze_mount_seela", u8"塞拉山脉", u8"极难"},
    {"ze_mountain_escape_p", u8"高山逃亡(剿匪)", u8"简单"},
    {"ze_mountain_escape_snow", u8"雪山大逃亡", u8"困难"},
    {"ze_mountain_ultimate", u8"终极爬山", u8"困难"},
    {"ze_namviet_p", u8"越南踩雷王", u8"普通"},
    {"ze_naruto_z", u8"火影村", u8"普通"},
    {"ze_necromanteion_p", u8"希腊神殿", u8"史诗"},
    {"ze_negative_legacy_a2", u8"消失的遗产", u8"困难"},
    {"ze_neko_canyon_p", u8"猫猫峡谷（剿匪）", u8"普通"},
    {"ze_neochrome", u8"霓铬", u8"极难"},
    {"ze_neovia", u8"Neovia工厂逃亡", u8"普通"},
    {"ze_neron", u8"盈能之境", u8"极难"},
    {"ze_new_italy_cs2", u8"新意大利", u8"普通"},
    {"ze_newyear_v18", u8"新年牢大逃亡", u8"简单"},
    {"ze_newyork_escape_p", u8"纽约大逃亡", u8"普通"},
    {"ze_nmzj_cs2", u8"牛魔战纪", u8"普通"},
    {"ze_no_name_v2_3", u8"进阶萌新综合练习图", u8"极难"},
    {"ze_no_title_cs2_l", u8"萌新综合练习图", u8"极难"},
    {"ze_noir_p", u8"黑色街道", u8"困难"},
    {"ze_nomada_z", u8"无限宫殿", u8"极难"},
    {"ze_notredame_p", u8"巴黎圣母院", u8"普通"},
    {"ze_npst_v8_gmod", u8"代号：黑山计划", u8"史诗"},
    {"ze_nuclear_site_survie_by_gm", u8"危机时刻", u8"困难"},
    {"ze_nuke_p", u8"核子基地", u8"简单"},
    {"ze_ny_marathon_cs2", u8"纽约马拉松大赛", u8"普通"},
    {"ze_ny_marathon_p", u8"纽约马拉松大赛(P组版)", u8"普通"},
    {"ze_obf_filth_v1", u8"代号：怒火中烧", u8"梦魇"},
    {"ze_obf_insane", u8"代号：烈火雄心", u8"梦魇"},
    {"ze_obf_npst_v2", u8"代号：牛批神图v2", u8"梦魇"},
    {"ze_obf_npst_v2_legacy", u8"代号：牛批神图v2经典版", u8"梦魇"},
    {"ze_obf_rampage_v2", u8"代号：野火燎原", u8"梦魇"},
    {"ze_obf_rampage_v2_legacy", u8"代号：横空出世-火之心", u8"梦魇"},
    {"ze_obf_rampage_v24", u8"代号：横空出世-最终幻想", u8"梦魇"},
    {"ze_obf_rescape", u8"代号：浴火重生", u8"梦魇"},
    {"ze_obff_npst_v24", u8"最中幻想2：尼赫伦斯", u8"梦魇"},
    {"ze_obj_abyss", u8"代号：暗流涌动", u8"梦魇"},
    {"ze_obj_abyss_v2", u8"代号：破渊之剑", u8"梦魇"},
    {"ze_obj_annihilate_dd_v1", u8"代号：孤注一掷", u8"绝境"},
    {"ze_obj_avulsion", u8"代号：分崩离析", u8"梦魇"},
    {"ze_obj_avulsion_a1", u8"代号：分崩离析", u8"梦魇"},
    {"ze_obj_blue_depth", u8"代号：蓝渊计划", u8"梦魇"},
    {"ze_obj_eclipsis", u8"代号：日蚀计划", u8"梦魇"},
    {"ze_obj_ember", u8"代号：绝境星火", u8"绝境"},
    {"ze_obj_encounter", u8"代号：争锋相对", u8"梦魇"},
    {"ze_obj_encounter_a2", u8"代号：针锋相对", u8"史诗"},
    {"ze_obj_escalation_a1", u8"代号：逆境飞升", u8"绝境"},
    {"ze_obj_escalation_v1", u8"代号：飞升计划", u8"梦魇"},
    {"ze_obj_federation", u8"代号：守望莱茵", u8"绝境"},
    {"ze_obj_goosestep_v1", u8"代号：缓兵之计", u8"梦魇"},
    {"ze_obj_ouroboros_apollyon", u8"【衔尾蛇计划】代号：辰宿归墟", u8"梦魇"},
    {"ze_obj_ouroboros_aurora", u8"【衔尾蛇计划】代号：落日余晖", u8"梦魇"},
    {"ze_obj_ouroboros_aurora_v2", u8"【衔尾蛇计划】代号：落日余晖-重生", u8"梦魇"},
    {"ze_obj_ouroboros_ragnarok", u8"【衔尾蛇计划】代号：破晓终幕", u8"梦魇"},
    {"ze_obj_rampage_v1_2", u8"代号：横空出世", u8"史诗"},
    {"ze_obj_redemption", u8"代号：一线生机", u8"梦魇"},
    {"ze_obj_redemption_v2", u8"代号：劫烬生曦", u8"梦魇"},
    {"ze_obj_redheart", u8"代号：灼日烛心", u8"梦魇"},
    {"ze_obj_redheart_v12", u8"代号：唤心之日", u8"梦魇"},
    {"ze_obj_rove_v1", u8"代号：永夜行疆", u8"梦魇"},
    {"ze_obj_vertigo_v1", u8"代号：劫后余生", u8"梦魇"},
    {"ze_obj_void_v1", u8"代号：至死不渝", u8"史诗"},
    {"ze_obj_void_v2", u8"代号：破釜沉舟", u8"梦魇"},
    {"ze_oblivion_castle", u8"遗忘城堡", u8"极难"},
    {"ze_ocarina_of_time", u8"塞尔达传说：时之笛", u8"普通"},
    {"ze_ocean_base_escape_p", u8"海底基地", u8"普通"},
    {"ze_ocean_heart_cs2", u8"海洋之心", u8"极难"},
    {"ze_offliner", u8"单机者", u8"极难"},
    {"ze_omega_p", u8"欧米茄", u8"普通"},
    {"ze_omen_cs2", u8"启示：命运预兆", u8"史诗"},
    {"ze_omochi_cs2", u8"元素的秘神", u8"极难"},
    {"ze_one_dream_machine", u8"梦想机器", u8"极难"},
    {"ze_oneiros_p", u8"奥涅伊洛斯", u8"极难"},
    {"ze_only_up", u8"Only Up!", u8"史诗"},
    {"ze_oot_shadowtemple", u8"塞尔达传说：时之笛(影之神殿)", u8"极难"},
    {"ze_opti_variety_missions_cs2_l", u8"不科学任务", u8"普通"},
    {"ze_otakuroom_pt", u8"御宅房", u8"普通"},
    {"ze_out_of_the_cinema", u8"飞常电影院", u8"困难"},
    {"ze_outlast", u8"逃生I", u8"极难"},
    {"ze_outpost_escape_p", u8"前哨基地逃亡", u8"普通"},
    {"ze_overkill_p", u8"赶尽杀绝", u8"困难"},
    {"ze_overlord", u8"不死者之王", u8"史诗"},
    {"ze_p_v_z", u8"植物大战僵尸", u8"极难"},
    {"ze_paindown", u8"殇渊", u8"极难"},
    {"ze_palace_adventure", u8"宫殿冒险", u8"困难"},
    {"ze_palace_of_minolila_cs2", u8"米诺莉拉神殿", u8"极难"},
    {"ze_panic_escape_p", u8"跳刀仓库", u8"普通"},
    {"ze_paradise_t", u8"天堂岛", u8"简单"},
    {"ze_paranoia_cs2", u8"浮生若梦", u8"史诗"},
    {"ze_parkers_pit_p", u8"帕克矿坑", u8"普通"},
    {"ze_parking_p", u8"逃离停车场大楼", u8"普通"},
    {"ze_parkour", u8"跑酷公园", u8"简单"},
    {"ze_payload_swarm", u8"负载运输逃亡", u8"极难"},
    {"ze_pc", u8"巨人机箱", u8"梦魇"},
    {"ze_pd2_crime_art", u8"收获日2：美术馆", u8"简单"},
    {"ze_peach_castle_n64", u8"碧姬公主城堡1", u8"梦魇"},
    {"ze_peach_insanity_n64", u8"碧姬公主城堡2", u8"梦魇"},
    {"ze_permafrost", u8"永冻之地", u8"史诗"},
    {"ze_pirates_port_royal", u8"加勒比海盗：罗亚尔港", u8"史诗"},
    {"ze_plants_vs_zombies", u8"植物大战僵尸（花园战争）", u8"史诗"},
    {"ze_platformer_p", u8"[娱乐]捡币b6", u8"普通"},
    {"ze_pokemon_johto", u8"精灵宝可梦：城都地区", u8"普通"},
    {"ze_pokemon_kanto_v1", u8"宝可梦道馆", u8"普通"},
    {"ze_pool_hollow", u8"空池", u8"普通"},
    {"ze_pools_p", u8"后室level130：荒谬泳池", u8"普通"},
    {"ze_pools_part2", u8"后室level130：荒谬泳池2", u8"极难"},
    {"ze_popkart_b3", u8"卡卡跑车丁", u8"普通"},
    {"ze_popkart_r", u8"卡卡跑车丁重置版", u8"普通"},
    {"ze_por_island_p", u8"刷分岛", u8"简单"},
    {"ze_portal_story_p", u8"传送门故事", u8"普通"},
    {"ze_postal_p", u8"夺命邮差", u8"困难"},
    {"ze_potc_p", u8"小加勒比", u8"普通"},
    {"ze_predator_ultimate_p", u8"铁血战士", u8"极难"},
    {"ze_pretender", u8"一只奶龙的旅行", u8"史诗"},
    {"ze_prey_bedroom", u8"猎物对决", u8"简单"},
    {"ze_prisonbreak_escape", u8"越狱：逃脱", u8"普通"},
    {"ze_prisonbreak_rescue", u8"越狱：拯救", u8"普通"},
    {"ze_project_codex_z", u8"彩虹圣典", u8"史诗"},
    {"ze_prototype", u8"虐杀原形", u8"普通"},
    {"ze_psycho_pass", u8"心理测量者", u8"史诗"},
    {"ze_purification_a1", u8"净化", u8"梦魇"},
    {"ze_puta_p", u8"PUTA工厂", u8"普通"},
    {"ze_quiver_p", u8"极地风暴", u8"困难"},
    {"ze_r_w_b_ulti", u8"红黑白的乐章", u8"极难"},
    {"rp_downtown", u8"EXG小镇", u8"绝境"},
    {"ze_r00ms", u8"房间", u8"困难"},
    {"ze_rabanastre_royal", u8"最终幻想12：王都拉巴纳斯塔", u8"极难"},
    {"ze_raccoon_facility_p", u8"生化危机：蜂巢", u8"简单"},
    {"ze_radio_building", u8"猛虎上山(电台大楼)", u8"简单"},
    {"ze_rainbow_factory", u8"彩虹工厂", u8"困难"},
    {"ze_raintime2_stormwindkeep_v3", u8"时雨2：暴风要塞", u8"极难"},
    {"ze_random_escape_p", u8"新随机大爆炸", u8"困难"},
    {"ze_random_p", u8"随机大爆炸", u8"困难"},
    {"ze_ratatouille", u8"美食总动员", u8"困难"},
    {"ze_rats_escape", u8"厨房逃亡", u8"困难"},
    {"ze_rawnscape_p", u8"罗恩逃亡", u8"普通"},
    {"ze_re_abydos", u8"碧蓝档案：总力战(新版)", u8"困难"},
    {"ze_re_creation", u8"复刻之界", u8"史诗"},
    {"ze_realm", u8"意境", u8"史诗"},
    {"ze_red_planet", u8"逃离红星", u8"困难"},
    {"ze_requiem_test", u8"镇魂曲", u8"极难"},
    {"ze_residence_of_cloud", u8"云中居", u8"普通"},
    {"ze_resident_evil_3", u8"生化危机3:复仇女神", u8"绝境"},
    {"ze_rien_z", u8"虚无之境", u8"极难"},
    {"ze_rizomata_p", u8"精灵塔:苍穹之诗", u8"史诗"},
    {"ze_rocket_escape_p", u8"火箭逃亡", u8"普通"},
    {"ze_rooftop_madness_p", u8"城市天际线[娱乐-剿匪]", u8"普通"},
    {"ze_rooftop_rogue_ws", u8"屋顶逃亡：长征版", u8"困难"},
    {"ze_rooftop_runaway1_p", u8"屋顶逃亡1", u8"简单"},
    {"ze_rooftop_runaway2_p", u8"屋顶逃亡2", u8"简单"},
    {"ze_rooftop_runaway3_xyy", u8"屋顶逃亡3", u8"普通"},
    {"ze_rt0_genesis_cs2", u8"时雨0：起源", u8"极难"},
    {"ze_rt1_torontoisland_cs2", u8"时雨1：多伦多岛", u8"极难"},
    {"ze_rtcw_ominous_rumors_p", u8"重返企鹅总部", u8"普通"},
    {"ze_rtv_one_more_p", u8"RTV再来一票", u8"简单"},
    {"ze_runaway_roofside1", u8"屋顶逃亡1:倒转地球", u8"普通"},
    {"ze_runaway_underroof2", u8"屋顶逃亡2:倒转地球", u8"普通"},
    {"ze_rush_a", u8"RUSH A！RUSH A！", u8"史诗"},
    {"ze_rush_b", u8"RUSH B！RUSH B！", u8"史诗"},
    {"ze_s_a_m", u8"刀剑神域", u8"史诗"},
    {"ze_sa2_pumpkin_hill", u8"[娱乐]万圣节游戏:南瓜山", u8"简单"},
    {"ze_sagreen_cs2", u8"沙绿逃亡", u8"梦魇"},
    {"ze_sakuzyo", u8"消除", u8"普通"},
    {"ze_samosbor", u8"笼子", u8"梦魇"},
    {"ze_sandstorm_cs2", u8"沙尘暴", u8"极难"},
    {"ze_santassination_p", u8"狮子王", u8"史诗"},
    {"ze_saw_p", u8"锯与魔法", u8"简单"},
    {"ze_sc_turtles", u8"乌龟岛之旅", u8"简单"},
    {"ze_scourge_p", u8"灾祸之源", u8"史诗"},
    {"ze_scp_containment_breach", u8"SCP收容失效", u8"极难"},
    {"ze_screaming_bells", u8"战锤末世鼠疫2：尖啸钟", u8"困难"},
    {"ze_secret_garden", u8"goobers的秘密花園", u8"普通"},
    {"ze_sele", u8"迷惘圣堂", u8"普通"},
    {"ze_serenity", u8"静谧之池", u8"普通"},
    {"ze_serpentis_temple", u8"美杜莎神庙", u8"史诗"},
    {"ze_sewer", u8"下水道", u8"简单"},
    {"ze_sewer_escape_p", u8"下水道逃亡", u8"简单"},
    {"ze_shadow_corridor", u8"影廊", u8"普通"},
    {"ze_shadow_moses", u8"合金装备5：影子摩西", u8"史诗"},
    {"ze_shaurma_v3", u8"东百往事", u8"困难"},
    {"ze_showdown_p", u8"巅峰对决", u8"普通"},
    {"ze_shrine_of_umos_xyy", u8"乌莫斯神庙", u8"极难"},
    {"ze_shroomforest_p", u8"蘑菇森林1", u8"普通"},
    {"ze_shroomforest2_p", u8"蘑菇森林2", u8"普通"},
    {"ze_shroomforest3_p_fix", u8"蘑菇森林3", u8"极难"},
    {"ze_siberia_1990_p", u8"西伯利亚1990", u8"普通"},
    {"ze_silent_hill_2_illusion", u8"寂静岭2:幻境", u8"困难"},
    {"ze_silent_hill_2_rengurn", u8"寂静岭：重返2", u8"困难"},
    {"ze_silent_hill_3_dawn", u8"寂静岭3:黎明", u8"普通"},
    {"ze_silent_hill_3_dawn_full", u8"寂静岭3:黎明完全版", u8"困难"},
    {"ze_silent_hill_3_flee", u8"寂静岭3:逃离", u8"困难"},
    {"ze_silent_hill_blackblood", u8"寂静岭：黑血", u8"普通"},
    {"ze_silent_hill_rengurn", u8"寂静岭：重返", u8"普通"},
    {"ze_silenthill_pt", u8"寂静岭：pt", u8"普通"},
    {"ze_simple_teamplay_p", u8"非常简单的团队游戏", u8"普通"},
    {"ze_sisyphus", u8"西西弗斯的历练", u8"绝境"},
    {"ze_sit_caelum_paradisus", u8"雕刻天堂", u8"困难"},
    {"ze_skill_escape_cs2", u8"身法大考验", u8"绝境"},
    {"ze_skill_escape_xmas", u8"身法大考验(圣诞版)", u8"绝境"},
    {"ze_sky_bridge_a01_fix3", u8"天空之桥", u8"困难"},
    {"ze_sky_defend", u8"天际防守", u8"梦魇"},
    {"ze_sky_fantasy_v1", u8"天空幻想v1", u8"极难"},
    {"ze_sky_fantasy_v2", u8"天空幻想v2", u8"极难"},
    {"ze_skygarden", u8"天穹树", u8"史诗"},
    {"ze_skyline", u8"逃出生天", u8"普通"},
    {"ze_skyscraper_city_p", u8"镜之边缘：大厦飞驰", u8"普通"},
    {"ze_slender_escape_p", u8"面条人：瘦长鬼影", u8"极难"},
    {"ze_solidarity_paper_cs2_l", u8"纸质基地", u8"普通"},
    {"ze_sorrento_arknights_cs2_l", u8"索伦托：明日方舟", u8"简单"},
    {"ze_sorrento_escape_p", u8"索伦托逃亡", u8"普通"},
    {"ze_space_flight_p", u8"宇宙空间站", u8"普通"},
    {"ze_squid_game", u8"[娱乐]鱿鱼游戏", u8"梦魇"},
    {"ze_sst2_p", u8"星河舰队2", u8"简单"},
    {"ze_stab_town_p", u8"小镇突袭", u8"普通"},
    {"ze_stalker_ultimate_v23", u8"潜行者:切尔诺贝利(V23)", u8"史诗"},
    {"ze_stalker_ultimate_z", u8"潜行者:切尔诺贝利", u8"史诗"},
    {"ze_stalkermonolith", u8"潜行者：黑石", u8"史诗"},
    {"ze_stardust_a03", u8"星尘", u8"极难"},
    {"ze_stark_escape", u8"史塔克逃亡", u8"困难"},
    {"ze_starlight_revue_cs2", u8"少女歌剧:命运舞台", u8"困难"},
    {"ze_starwars_v2fix", u8"星球大战v2fix", u8"极难"},
    {"ze_steyliff_grove", u8"最终幻想15：斯基利弗樹林迷宫(低伤害刀)", u8"史诗"},
    {"ze_steyliff_grove_r", u8"最终幻想15：斯基利弗樹林迷宫(重置版)", u8"困难"},
    {"ze_stilshrine_of_miriam", u8"最终幻想12：米利暗遗迹", u8"极难"},
    {"ze_strange_escape_p", u8"绝境逃亡", u8"普通"},
    {"ze_summer_house", u8"绚夏别墅", u8"普通"},
    {"ze_summer_warehouse", u8"夏日仓库", u8"普通"},
    {"ze_sunkentemple", u8"魔兽世界：淹没神庙", u8"困难"},
    {"ze_survivors_mountain", u8"幸存者", u8"普通"},
    {"ze_system_cs2_l", u8"系统小游戏", u8"困难"},
    {"ze_temple_escape_p", u8"神庙逃亡", u8"普通"},
    {"ze_temple_raider", u8"神庙急袭", u8"困难"},
    {"ze_tenkinoko_welkin_z", u8"天气之子", u8"极难"},
    {"ze_tesv_skyrim_p", u8"上古卷轴：天际", u8"史诗"},
    {"ze_texturescape_cs2_l", u8"坑爹逃亡", u8"普通"},
    {"ze_the_curse_of_blackwater", u8"黑水镇的诅咒", u8"史诗"},
    {"ze_thelostworld_redux_p", u8"侏罗纪公园：失落之岛", u8"简单"},
    {"ze_thorn_final_song", u8"代号：荆棘挽歌", u8"梦魇"},
    {"ze_thorny_torch", u8"代号：荆棘薪火", u8"梦魇"},
    {"ze_thousand_steps_p", u8"千层阶梯", u8"普通"},
    {"ze_three_eyes", u8"三眼", u8"史诗"},
    {"ze_thriller_escape_p", u8"逃离惊悚电影院", u8"普通"},
    {"ze_tilex_escape_p", u8"列车逃亡", u8"普通"},
    {"ze_tilex_ultimate_p", u8"跳刀列车", u8"史诗"},
    {"ze_timeshifter", u8"时空行者", u8"史诗"},
    {"ze_timesink", u8"时之沙", u8"史诗"},
    {"ze_timesplitters_p", u8"时空撕裂者", u8"普通"},
    {"ze_titanic_escape_p", u8"泰坦尼克号", u8"简单"},
    {"ze_titanic_sweet_dreams", u8"梦中的泰坦尼克号", u8"普通"},
    {"ze_tkara_p", u8"塔卡拉基地", u8"普通"},
    {"ze_toaster_p", u8"面包机", u8"极难"},
    {"ze_toggle_theory", u8"绯蓝节奏", u8"极难"},
    {"ze_totemo_roka_p", u8"神秘海域", u8"困难"},
    {"ze_townscapes", u8"小镇逃亡", u8"简单"},
    {"ze_toy_world_final", u8"玩具世界", u8"困难"},
    {"ze_traak_p", u8"逃命游轮", u8"普通"},
    {"ze_trainescape_p", u8"火车逃亡", u8"简单"},
    {"ze_trainsanity", u8"火车通路", u8"困难"},
    {"ze_tranquility", u8"崇寂之渊", u8"普通"},
    {"ze_transformers_pyramid", u8"变形金刚:金字塔", u8"普通"},
    {"ze_trepang", u8"地平线行动", u8"史诗"},
    {"ze_tyranny_cs2", u8"暴君1", u8"极难"},
    {"ze_tyranny2", u8"暴君2：新魔典纪元", u8"史诗"},
    {"ze_uchiha_legacy", u8"宇智波：遗响", u8"史诗"},
    {"ze_ultra_ungent_a2_cs2", u8"超级跳绳王", u8"极难"},
    {"ze_ultrakill", u8"疯狂连杀", u8"史诗"},
    {"ze_umbra", u8"法环：幽冕", u8"梦魇"},
    {"ze_umbrella_zombie", u8"保护伞公司", u8"困难"},
    {"ze_umbrellazombie_v1_p3_final", u8"保护伞公司3", u8"普通"},
    {"ze_umbrellazombie_v1_part2_1", u8"保护伞公司2", u8"普通"},
    {"ze_umbrellazombiezmtr_v1", u8"保护伞公司1", u8"普通"},
    {"ze_undead_shrine_p", u8"亡灵神殿", u8"极难"},
    {"ze_undertale_sans_final", u8"传说之下：san战", u8"困难"},
    {"ze_unfulfilled_ambition", u8"未竟之志", u8"极难"},
    {"ze_untitled_touhou", u8"东方妖妖梦", u8"普通"},
    {"ze_upwards_p", u8"步步高升", u8"普通"},
    {"ze_uranus_attack", u8"诅咒熊传说:天熊下凡", u8"史诗"},
    {"ze_urban_laby_of_death_p", u8"城市迷宫", u8"普通"},
    {"ze_urbanstone", u8"石头城市", u8"史诗"},
    {"ze_ut2004_convoy_p", u8"虚幻竞技场", u8"极难"},
    {"ze_uyuni", u8"天空之境：乌尤尼", u8"史诗"},
    {"ze_v0u0v_p", u8"颜文字2 - v0u0v", u8"梦魇"},
    {"ze_variis", u8"影子人之谜", u8"普通"},
    {"ze_venice_escape_p", u8"威尼斯老家", u8"简单"},
    {"ze_verdant", u8"翠幕蔽影", u8"困难"},
    {"ze_vietnam_p", u8"越南雨林", u8"简单"},
    {"ze_virtual_insanity_v1", u8"错乱疯狂", u8"普通"},
    {"ze_visualizer", u8"监视者", u8"史诗"},
    {"ze_voodoo_islands_p", u8"巫毒岛", u8"简单"},
    {"ze_voodoo_xtrem_islands", u8"巫毒岛终极版", u8"困难"},
    {"ze_watagi_sanatorium", u8"渡木疗养所", u8"普通"},
    {"ze_watagi_tunnel_rewind", u8"渡木隧道探险", u8"普通"},
    {"ze_waterpark", u8"长隆水上乐园", u8"普通"},
    {"ze_wicked_organization", u8"邪惡组织", u8"普通"},
    {"ze_winter", u8"凛冬小镇", u8"简单"},
    {"ze_winter_house", u8"冬日之家", u8"普通"},
    {"ze_winter_warehouse_p", u8"冰雪牢缘", u8"简单"},
    {"ze_world_escapes", u8"世界逃亡", u8"普通"},
    {"ze_x_game_room", u8"电竞房", u8"困难"},
    {"ze_xenovation", u8"异界终章", u8"史诗"},
    {"ze_xiii_winslow_bank", u8"金库惊魂", u8"普通"},
    {"ze_xuyanzhiting", u8"虚掩之庭", u8"普通"},
    {"ze_xuyanzhiting_jiushu", u8"虚掩之庭：救赎", u8"简单"},
    {"ze_xuyanzhiting_qy", u8"代号：虚掩之庭", u8"极难"},
    {"ze_yurilnier", u8"幽莉兰尼尔雪域之城", u8"普通"},
    {"ze_yueyingchuanshuo_cs2", u8"月影传说", u8"史诗"},
    {"ze_zandalar_forever", u8"赞达拉万古长存", u8"史诗"},
    {"ze_zertinan", u8"最终幻想12：泽尔提南", u8"史诗"},
    {"ze_zk_fapescape_p", u8"小乐高逃亡", u8"简单"},
    {"ze_zk_mall_of_zombies_p", u8"购物中心", u8"普通"},
    {"ze_zombie_scenario_lostcity", u8"大灾变：失落之城", u8"普通"},
    {"ze_zombiemod_corporation_p", u8"扛水塔", u8"简单"},
    {"ze_zombierig_p", u8"钻井平台", u8"普通"},
    {"ze_mkzk_scarab_v4_remake", u8"重生之我在ZE倒斗-究极无敌折磨之圣甲虫法老王金字塔V4魔改版", u8"绝境"},
};
const QHash<QString,QString> &table() {
    static const QHash<QString,QString> t = [] {
        QHash<QString,QString> h;
        for (const auto &e : kTranslations)
            h.insert(QString::fromLatin1(e.name), QString::fromUtf8(e.zh));
        return h;
    }();
    return t;
}
const QHash<QString,QString> &diffTable() {
    static const QHash<QString,QString> t = [] {
        QHash<QString,QString> h;
        for (const auto &e : kTranslations)
            h.insert(QString::fromLatin1(e.name), QString::fromUtf8(e.diff));
        return h;
    }();
    return t;
}
}

bool MapTranslator::s_enMode = false;

void MapTranslator::setEnglish(bool en) {
    s_enMode = en;
}

QString MapTranslator::formatMap(const QString &name) {
    if (name.isEmpty())
        return QStringLiteral("--");
    if (s_enMode)
        return name;
    QString zh = table().value(name);
    if (zh.isEmpty()) {

        QString alt = name;
        if (alt.endsWith(QLatin1String("_p"))) alt.chop(2);
        else alt += QLatin1String("_p");
        zh = table().value(alt);
    }
    if (!zh.isEmpty())
        return name + QStringLiteral("\u300c") + zh + QStringLiteral("\u300d");
    return name;
}

QString MapTranslator::difficulty(const QString &name) {
    if (name.isEmpty())
        return QString();
    QString d = diffTable().value(name);
    if (d.isEmpty()) {
        QString alt = name;
        if (alt.endsWith(QLatin1String("_p"))) alt.chop(2);
        else alt += QLatin1String("_p");
        d = diffTable().value(alt);
    }
    return d;
}


QString MapTranslator::zhName(const QString &name) {
    if (name.isEmpty())
        return QString();
    QString zh = table().value(name);
    if (zh.isEmpty()) {
        QString alt = name;
        if (alt.endsWith(QLatin1String("_p"))) alt.chop(2);
        else alt += QLatin1String("_p");
        zh = table().value(alt);
    }
    return zh.isEmpty() ? name : zh;
}


QString translateMapZh(const QString &name) {
    QString zh = table().value(name);
    if (zh.isEmpty()) {
        QString alt = name;
        if (alt.endsWith(QLatin1String("_p"))) alt.chop(2);
        else alt += QLatin1String("_p");
        zh = table().value(alt);
    }
    return zh;
}
QStringList mapTranslationNames() { return table().keys(); }

void MapTranslator::copyText(const QString &text)
{
    if (text.isEmpty())
        return;
    QGuiApplication::clipboard()->setText(text);
}
